---
# tasks file for apache
- name: Install Apache
  apt: name={{ item }} state=latest update_cache=yes cache_valid_time=300
  with_items:
    - apache2

- stat: path=/var/www
  register: p

- name: remove apache root Folder
  file: path=/var/www state=absent
  when: p.stat.isdir is defined and p.stat.isdir == true

- name: Create Web Directory
  file: path={{ oxid_root }} state=directory

- name: Link Vagrant folder to apache root
  file: src={{ oxid_root }}/source dest=/var/www state=link force=yes

- name: Copy default vhost config
  template: src=default dest=/etc/apache2/sites-available/default mode=0644 owner=root group=root
  notify: Restart Apache

- name: Enable Apache Rewrite Module
  apache2_module: name=rewrite state=present

- name: Add Apache user to vagrant group
  user: name=www-data groups=vagrant,www-data