---
# tasks file for apache
- name: Install Apache
  apt: name={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - apache2

- name: Create Web Directory
  file: path={{ apache_web_root }} state=directory

- name: Copy default vhost config
  template: src=default dest=/etc/apache2/sites-available/default mode=0644 owner=root group=root
  notify: Restart Apache

- name: Enable Apache Rewrite Module
  apache2_module: name={{ item }} state=present
  with_items:
    - rewrite

- name: Add Apache user to vagrant group
  user: name={{ apache_user }} groups=vagrant,{{ apache_user }}
