---
- name: Install Unzip
  apt: name=unzip state=latest update_cache=yes cache_valid_time=3600

- stat: path={{ oxid_root }}
  register: p

- name: copy Oxid files to {{ oxid_root }}
  unarchive: src=OXID_ESHOP_CE_4.8.6.zip dest={{ oxid_root }} creates={{ oxid_root }}/application

- name: Remove Exception log
  file: path={{ oxid_root }}/log/EXCEPTION_LOG.txt state=touch owner=www-data group=www-data mode=0777

- name: Changing Directory Rights {{ apache_user }}:{{ apache_user }}
  file: path={{ oxid_root }}/{{ item }} mode=0777 recurse=yes state=directory owner={{ apache_user }} group={{ apache_user }}
  with_items:
    - out/pictures
    - out/media
    - log
    - tmp
    - export

- name: Changing file Rights to {{ apache_user }}:{{ apache_user }}
  file: path={{ oxid_root }}/{{ item }} mode=0777 owner={{ apache_user }} group={{ apache_user }}
  with_items:
    - .htaccess
    - config.inc.php

- name: Copy database dump to server
  copy: src=oxid_dump.sql dest=/tmp/oxid_dump.sql

#- name: Create database {{ oxid_database_name }}
#  mysql_db: name={{ oxid_database_name }} state=import target=/tmp/oxid_dump.sql

#- name: Copy oxid config file (config.inc.php)
#  template: src=config.inc.php dest={{ oxid_root }}/config.inc.php

- name: Remove setup directory
  file: name={{ oxid_root }}/setup state=absent