#http://download.oxid-esales.com/ce/index.php
---
- hosts: all
  sudo: yes
  vars:
    - apache_web_root: /vagrant/web
    - mysql_user_name: vagrant
    - mysql_user_name: vagrant
    - mysql_root_password: root
    - oxid_idebug: 1

  roles:
    - common
    - mysql
    - apache
    - php
    - oxid
    - phpmyadmin
    - nodejs
